// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//protoc   --proto_path=.  --micro_out=.  --go_out=. ./*.proto
type CheckLoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginReq) Reset()         { *m = CheckLoginReq{} }
func (m *CheckLoginReq) String() string { return proto.CompactTextString(m) }
func (*CheckLoginReq) ProtoMessage()    {}
func (*CheckLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *CheckLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginReq.Unmarshal(m, b)
}
func (m *CheckLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginReq.Marshal(b, m, deterministic)
}
func (m *CheckLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginReq.Merge(m, src)
}
func (m *CheckLoginReq) XXX_Size() int {
	return xxx_messageInfo_CheckLoginReq.Size(m)
}
func (m *CheckLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginReq proto.InternalMessageInfo

func (m *CheckLoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckLoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type CheckLoginRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginRsp) Reset()         { *m = CheckLoginRsp{} }
func (m *CheckLoginRsp) String() string { return proto.CompactTextString(m) }
func (*CheckLoginRsp) ProtoMessage()    {}
func (*CheckLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *CheckLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginRsp.Unmarshal(m, b)
}
func (m *CheckLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginRsp.Marshal(b, m, deterministic)
}
func (m *CheckLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginRsp.Merge(m, src)
}
func (m *CheckLoginRsp) XXX_Size() int {
	return xxx_messageInfo_CheckLoginRsp.Size(m)
}
func (m *CheckLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginRsp proto.InternalMessageInfo

func (m *CheckLoginRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *CheckLoginRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterUsrReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUsrReq) Reset()         { *m = RegisterUsrReq{} }
func (m *RegisterUsrReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUsrReq) ProtoMessage()    {}
func (*RegisterUsrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *RegisterUsrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsrReq.Unmarshal(m, b)
}
func (m *RegisterUsrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsrReq.Marshal(b, m, deterministic)
}
func (m *RegisterUsrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsrReq.Merge(m, src)
}
func (m *RegisterUsrReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUsrReq.Size(m)
}
func (m *RegisterUsrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsrReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsrReq proto.InternalMessageInfo

func (m *RegisterUsrReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUsrReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *RegisterUsrReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type RegisterUsrRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUsrRsp) Reset()         { *m = RegisterUsrRsp{} }
func (m *RegisterUsrRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUsrRsp) ProtoMessage()    {}
func (*RegisterUsrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *RegisterUsrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsrRsp.Unmarshal(m, b)
}
func (m *RegisterUsrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsrRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUsrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsrRsp.Merge(m, src)
}
func (m *RegisterUsrRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUsrRsp.Size(m)
}
func (m *RegisterUsrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsrRsp proto.InternalMessageInfo

func (m *RegisterUsrRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *RegisterUsrRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUsrRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type ResetPwdReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPwdReq) Reset()         { *m = ResetPwdReq{} }
func (m *ResetPwdReq) String() string { return proto.CompactTextString(m) }
func (*ResetPwdReq) ProtoMessage()    {}
func (*ResetPwdReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{4}
}

func (m *ResetPwdReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPwdReq.Unmarshal(m, b)
}
func (m *ResetPwdReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPwdReq.Marshal(b, m, deterministic)
}
func (m *ResetPwdReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPwdReq.Merge(m, src)
}
func (m *ResetPwdReq) XXX_Size() int {
	return xxx_messageInfo_ResetPwdReq.Size(m)
}
func (m *ResetPwdReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPwdReq.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPwdReq proto.InternalMessageInfo

func (m *ResetPwdReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResetPwdReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type ResetPwdRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPwdRsp) Reset()         { *m = ResetPwdRsp{} }
func (m *ResetPwdRsp) String() string { return proto.CompactTextString(m) }
func (*ResetPwdRsp) ProtoMessage()    {}
func (*ResetPwdRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{5}
}

func (m *ResetPwdRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPwdRsp.Unmarshal(m, b)
}
func (m *ResetPwdRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPwdRsp.Marshal(b, m, deterministic)
}
func (m *ResetPwdRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPwdRsp.Merge(m, src)
}
func (m *ResetPwdRsp) XXX_Size() int {
	return xxx_messageInfo_ResetPwdRsp.Size(m)
}
func (m *ResetPwdRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPwdRsp.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPwdRsp proto.InternalMessageInfo

func (m *ResetPwdRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *ResetPwdRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ResetPwdRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CheckUsrEmailReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsrEmailReq) Reset()         { *m = CheckUsrEmailReq{} }
func (m *CheckUsrEmailReq) String() string { return proto.CompactTextString(m) }
func (*CheckUsrEmailReq) ProtoMessage()    {}
func (*CheckUsrEmailReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{6}
}

func (m *CheckUsrEmailReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsrEmailReq.Unmarshal(m, b)
}
func (m *CheckUsrEmailReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsrEmailReq.Marshal(b, m, deterministic)
}
func (m *CheckUsrEmailReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsrEmailReq.Merge(m, src)
}
func (m *CheckUsrEmailReq) XXX_Size() int {
	return xxx_messageInfo_CheckUsrEmailReq.Size(m)
}
func (m *CheckUsrEmailReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsrEmailReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsrEmailReq proto.InternalMessageInfo

func (m *CheckUsrEmailReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckUsrEmailReq) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type CheckUsrEmailRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckUsrEmailRsp) Reset()         { *m = CheckUsrEmailRsp{} }
func (m *CheckUsrEmailRsp) String() string { return proto.CompactTextString(m) }
func (*CheckUsrEmailRsp) ProtoMessage()    {}
func (*CheckUsrEmailRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{7}
}

func (m *CheckUsrEmailRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckUsrEmailRsp.Unmarshal(m, b)
}
func (m *CheckUsrEmailRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckUsrEmailRsp.Marshal(b, m, deterministic)
}
func (m *CheckUsrEmailRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckUsrEmailRsp.Merge(m, src)
}
func (m *CheckUsrEmailRsp) XXX_Size() int {
	return xxx_messageInfo_CheckUsrEmailRsp.Size(m)
}
func (m *CheckUsrEmailRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckUsrEmailRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckUsrEmailRsp proto.InternalMessageInfo

func (m *CheckUsrEmailRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *CheckUsrEmailRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckUsrEmailRsp) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckLoginReq)(nil), "dbproto.CheckLoginReq")
	proto.RegisterType((*CheckLoginRsp)(nil), "dbproto.CheckLoginRsp")
	proto.RegisterType((*RegisterUsrReq)(nil), "dbproto.RegisterUsrReq")
	proto.RegisterType((*RegisterUsrRsp)(nil), "dbproto.RegisterUsrRsp")
	proto.RegisterType((*ResetPwdReq)(nil), "dbproto.ResetPwdReq")
	proto.RegisterType((*ResetPwdRsp)(nil), "dbproto.ResetPwdRsp")
	proto.RegisterType((*CheckUsrEmailReq)(nil), "dbproto.CheckUsrEmailReq")
	proto.RegisterType((*CheckUsrEmailRsp)(nil), "dbproto.CheckUsrEmailRsp")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 297 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x41, 0x4f, 0xb3, 0x40,
	0x10, 0xfd, 0xca, 0x67, 0xab, 0x8c, 0xd1, 0x98, 0x89, 0xa9, 0xc8, 0xc9, 0x70, 0xf2, 0xc4, 0x41,
	0x4f, 0x44, 0x63, 0xa2, 0xd5, 0x78, 0xd1, 0x84, 0xac, 0xe9, 0x0f, 0x80, 0x32, 0xa1, 0x44, 0x0b,
	0xb8, 0x4b, 0xec, 0xff, 0xf0, 0x17, 0x1b, 0xa6, 0xb8, 0x65, 0x0d, 0x1c, 0x88, 0xde, 0x76, 0xde,
	0xf2, 0xde, 0x3c, 0xde, 0x3e, 0xd8, 0x4b, 0x62, 0xbf, 0x94, 0x45, 0x55, 0xe0, 0x6e, 0x12, 0xf3,
	0xc1, 0xbb, 0x82, 0x83, 0xd9, 0x92, 0x16, 0xaf, 0x4f, 0x45, 0x9a, 0xe5, 0x82, 0xde, 0x11, 0x61,
	0x27, 0x8f, 0x56, 0xe4, 0x8c, 0xce, 0x46, 0xe7, 0xb6, 0xe0, 0x33, 0x4e, 0x61, 0x52, 0x46, 0x4a,
	0xad, 0x13, 0xc7, 0x62, 0xb4, 0x99, 0xbc, 0xc0, 0x20, 0xab, 0x12, 0x8f, 0x61, 0x4c, 0x52, 0x66,
	0x09, 0xb3, 0xc7, 0x62, 0x33, 0x68, 0x49, 0x6b, 0x2b, 0xe9, 0x09, 0x38, 0x14, 0x94, 0x66, 0xaa,
	0x22, 0x39, 0x57, 0x72, 0xe0, 0x62, 0xde, 0xb3, 0x8a, 0xb2, 0x37, 0xe7, 0x3f, 0xc3, 0x9b, 0xc1,
	0x0b, 0x4d, 0xcd, 0x21, 0x7e, 0x7a, 0x14, 0x03, 0xd8, 0x17, 0xa4, 0xa8, 0x0a, 0xd7, 0xc9, 0xd0,
	0x6c, 0x9e, 0x5b, 0xd4, 0x3f, 0x70, 0x72, 0x0d, 0x47, 0x1c, 0xf5, 0x5c, 0xc9, 0x87, 0x1a, 0xe8,
	0xb3, 0xa3, 0xd9, 0x56, 0x9b, 0x2d, 0x7e, 0xb2, 0x7f, 0xef, 0xe8, 0xe2, 0xd3, 0x02, 0xfb, 0xfe,
	0xee, 0x85, 0xe4, 0x47, 0xb6, 0x20, 0xbc, 0x01, 0xd8, 0x56, 0x01, 0xa7, 0x7e, 0xd3, 0x2f, 0xdf,
	0x28, 0x97, 0xdb, 0x89, 0xab, 0xd2, 0xfb, 0x87, 0xb7, 0x75, 0x5c, 0xfa, 0xed, 0xf0, 0x44, 0x7f,
	0x68, 0xb6, 0xc4, 0xed, 0xbe, 0x60, 0x89, 0xc7, 0xa6, 0x8d, 0xdf, 0x3f, 0x89, 0xa7, 0xe6, 0xb6,
	0x56, 0x74, 0x6e, 0xdf, 0x15, 0x0b, 0x05, 0x60, 0xcf, 0x96, 0x51, 0x9e, 0x52, 0x58, 0x57, 0xad,
	0xb5, 0x50, 0x37, 0xc1, 0xed, 0x40, 0x6b, 0x6a, 0x3c, 0x61, 0xf0, 0xf2, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x2e, 0xe8, 0xf4, 0x4c, 0x6a, 0x03, 0x00, 0x00,
}
