// Code generated by protoc-gen-go. DO NOT EDIT.
// source: db.proto

package dbproto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//protoc   --proto_path=.  --micro_out=.  --go_out=. ./*.proto
type CheckLoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginReq) Reset()         { *m = CheckLoginReq{} }
func (m *CheckLoginReq) String() string { return proto.CompactTextString(m) }
func (*CheckLoginReq) ProtoMessage()    {}
func (*CheckLoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{0}
}

func (m *CheckLoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginReq.Unmarshal(m, b)
}
func (m *CheckLoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginReq.Marshal(b, m, deterministic)
}
func (m *CheckLoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginReq.Merge(m, src)
}
func (m *CheckLoginReq) XXX_Size() int {
	return xxx_messageInfo_CheckLoginReq.Size(m)
}
func (m *CheckLoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginReq proto.InternalMessageInfo

func (m *CheckLoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckLoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type CheckLoginRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckLoginRsp) Reset()         { *m = CheckLoginRsp{} }
func (m *CheckLoginRsp) String() string { return proto.CompactTextString(m) }
func (*CheckLoginRsp) ProtoMessage()    {}
func (*CheckLoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{1}
}

func (m *CheckLoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckLoginRsp.Unmarshal(m, b)
}
func (m *CheckLoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckLoginRsp.Marshal(b, m, deterministic)
}
func (m *CheckLoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckLoginRsp.Merge(m, src)
}
func (m *CheckLoginRsp) XXX_Size() int {
	return xxx_messageInfo_CheckLoginRsp.Size(m)
}
func (m *CheckLoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckLoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_CheckLoginRsp proto.InternalMessageInfo

func (m *CheckLoginRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *CheckLoginRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegisterUsrReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUsrReq) Reset()         { *m = RegisterUsrReq{} }
func (m *RegisterUsrReq) String() string { return proto.CompactTextString(m) }
func (*RegisterUsrReq) ProtoMessage()    {}
func (*RegisterUsrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{2}
}

func (m *RegisterUsrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsrReq.Unmarshal(m, b)
}
func (m *RegisterUsrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsrReq.Marshal(b, m, deterministic)
}
func (m *RegisterUsrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsrReq.Merge(m, src)
}
func (m *RegisterUsrReq) XXX_Size() int {
	return xxx_messageInfo_RegisterUsrReq.Size(m)
}
func (m *RegisterUsrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsrReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsrReq proto.InternalMessageInfo

func (m *RegisterUsrReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegisterUsrReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type RegisterUsrRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisterUsrRsp) Reset()         { *m = RegisterUsrRsp{} }
func (m *RegisterUsrRsp) String() string { return proto.CompactTextString(m) }
func (*RegisterUsrRsp) ProtoMessage()    {}
func (*RegisterUsrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_8817812184a13374, []int{3}
}

func (m *RegisterUsrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterUsrRsp.Unmarshal(m, b)
}
func (m *RegisterUsrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterUsrRsp.Marshal(b, m, deterministic)
}
func (m *RegisterUsrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterUsrRsp.Merge(m, src)
}
func (m *RegisterUsrRsp) XXX_Size() int {
	return xxx_messageInfo_RegisterUsrRsp.Size(m)
}
func (m *RegisterUsrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterUsrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterUsrRsp proto.InternalMessageInfo

func (m *RegisterUsrRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *RegisterUsrRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CheckLoginReq)(nil), "dbproto.CheckLoginReq")
	proto.RegisterType((*CheckLoginRsp)(nil), "dbproto.CheckLoginRsp")
	proto.RegisterType((*RegisterUsrReq)(nil), "dbproto.RegisterUsrReq")
	proto.RegisterType((*RegisterUsrRsp)(nil), "dbproto.RegisterUsrRsp")
}

func init() { proto.RegisterFile("db.proto", fileDescriptor_8817812184a13374) }

var fileDescriptor_8817812184a13374 = []byte{
	// 198 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x48, 0x49, 0xd2, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0x49, 0x02, 0x33, 0x94, 0xac, 0xb9, 0x78, 0x9d, 0x33,
	0x52, 0x93, 0xb3, 0x7d, 0xf2, 0xd3, 0x33, 0xf3, 0x82, 0x52, 0x0b, 0x85, 0x84, 0xb8, 0x58, 0xf2,
	0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x31, 0x2e, 0xb6,
	0x82, 0xc4, 0xe2, 0xe2, 0xf2, 0x14, 0x09, 0x26, 0xb0, 0x28, 0x94, 0xa7, 0x64, 0x89, 0xa2, 0xb9,
	0xb8, 0x40, 0x48, 0x84, 0x8b, 0x35, 0xb5, 0xa8, 0x28, 0x33, 0x05, 0xac, 0x9b, 0x35, 0x08, 0xc2,
	0x81, 0x1b, 0xc9, 0x84, 0x30, 0x52, 0xc9, 0x86, 0x8b, 0x2f, 0x28, 0x35, 0x3d, 0xb3, 0xb8, 0x24,
	0xb5, 0x28, 0xb4, 0xb8, 0x88, 0x54, 0x8b, 0xad, 0x50, 0x75, 0x93, 0x62, 0xb3, 0x51, 0x1f, 0x23,
	0x17, 0xa7, 0x8b, 0x53, 0x70, 0x6a, 0x51, 0x59, 0x66, 0x72, 0xaa, 0x90, 0x1d, 0x17, 0x17, 0xc2,
	0x0b, 0x42, 0x62, 0x7a, 0xd0, 0x70, 0xd1, 0x43, 0x09, 0x14, 0x29, 0xac, 0xe2, 0xc5, 0x05, 0x4a,
	0x0c, 0x42, 0x8e, 0x5c, 0xdc, 0x48, 0x2e, 0x11, 0x12, 0x87, 0x2b, 0x44, 0xf5, 0x9d, 0x14, 0x76,
	0x09, 0x90, 0x11, 0x49, 0x6c, 0x60, 0x71, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x81,
	0xbd, 0x07, 0x9e, 0x01, 0x00, 0x00,
}
