// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package loginproto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//protoc   --proto_path=.  --micro_out=.  --go_out=. ./*.proto
type LoginReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginReq) Reset()         { *m = LoginReq{} }
func (m *LoginReq) String() string { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()    {}
func (*LoginReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *LoginReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginReq.Unmarshal(m, b)
}
func (m *LoginReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginReq.Marshal(b, m, deterministic)
}
func (m *LoginReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginReq.Merge(m, src)
}
func (m *LoginReq) XXX_Size() int {
	return xxx_messageInfo_LoginReq.Size(m)
}
func (m *LoginReq) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginReq.DiscardUnknown(m)
}

var xxx_messageInfo_LoginReq proto.InternalMessageInfo

func (m *LoginReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LoginReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type LoginRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRsp) Reset()         { *m = LoginRsp{} }
func (m *LoginRsp) String() string { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()    {}
func (*LoginRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *LoginRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRsp.Unmarshal(m, b)
}
func (m *LoginRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRsp.Marshal(b, m, deterministic)
}
func (m *LoginRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRsp.Merge(m, src)
}
func (m *LoginRsp) XXX_Size() int {
	return xxx_messageInfo_LoginRsp.Size(m)
}
func (m *LoginRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRsp.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRsp proto.InternalMessageInfo

func (m *LoginRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *LoginRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RegUsrReq struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Passwd               string   `protobuf:"bytes,2,opt,name=passwd,proto3" json:"passwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegUsrReq) Reset()         { *m = RegUsrReq{} }
func (m *RegUsrReq) String() string { return proto.CompactTextString(m) }
func (*RegUsrReq) ProtoMessage()    {}
func (*RegUsrReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *RegUsrReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegUsrReq.Unmarshal(m, b)
}
func (m *RegUsrReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegUsrReq.Marshal(b, m, deterministic)
}
func (m *RegUsrReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegUsrReq.Merge(m, src)
}
func (m *RegUsrReq) XXX_Size() int {
	return xxx_messageInfo_RegUsrReq.Size(m)
}
func (m *RegUsrReq) XXX_DiscardUnknown() {
	xxx_messageInfo_RegUsrReq.DiscardUnknown(m)
}

var xxx_messageInfo_RegUsrReq proto.InternalMessageInfo

func (m *RegUsrReq) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RegUsrReq) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

type RegUsrRsp struct {
	Errid                int32    `protobuf:"varint,1,opt,name=errid,proto3" json:"errid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegUsrRsp) Reset()         { *m = RegUsrRsp{} }
func (m *RegUsrRsp) String() string { return proto.CompactTextString(m) }
func (*RegUsrRsp) ProtoMessage()    {}
func (*RegUsrRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *RegUsrRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegUsrRsp.Unmarshal(m, b)
}
func (m *RegUsrRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegUsrRsp.Marshal(b, m, deterministic)
}
func (m *RegUsrRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegUsrRsp.Merge(m, src)
}
func (m *RegUsrRsp) XXX_Size() int {
	return xxx_messageInfo_RegUsrRsp.Size(m)
}
func (m *RegUsrRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_RegUsrRsp.DiscardUnknown(m)
}

var xxx_messageInfo_RegUsrRsp proto.InternalMessageInfo

func (m *RegUsrRsp) GetErrid() int32 {
	if m != nil {
		return m.Errid
	}
	return 0
}

func (m *RegUsrRsp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "loginproto.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "loginproto.LoginRsp")
	proto.RegisterType((*RegUsrReq)(nil), "loginproto.RegUsrReq")
	proto.RegisterType((*RegUsrRsp)(nil), "loginproto.RegUsrRsp")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x02, 0x73, 0xc0, 0x6c, 0x25, 0x33, 0x2e,
	0x0e, 0x1f, 0x10, 0x2f, 0x28, 0xb5, 0x50, 0x48, 0x88, 0x8b, 0x25, 0x2f, 0x31, 0x37, 0x55, 0x82,
	0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x48, 0x2c, 0x2e, 0x2e,
	0x4f, 0x91, 0x60, 0x02, 0x8b, 0x42, 0x79, 0x4a, 0x26, 0x30, 0x7d, 0xc5, 0x05, 0x42, 0x22, 0x5c,
	0xac, 0xa9, 0x45, 0x45, 0x99, 0x29, 0x60, 0x8d, 0xac, 0x41, 0x10, 0x0e, 0xdc, 0x34, 0x26, 0x84,
	0x69, 0x4a, 0xe6, 0x5c, 0x9c, 0x41, 0xa9, 0xe9, 0xa1, 0xc5, 0x45, 0xa4, 0x5a, 0x67, 0x0a, 0xd7,
	0x48, 0x8a, 0x7d, 0x46, 0x0d, 0x8c, 0x5c, 0x1c, 0xa1, 0xc5, 0x45, 0x60, 0x97, 0x0a, 0x99, 0x72,
	0xb1, 0x42, 0x18, 0x22, 0x7a, 0x88, 0x00, 0xd0, 0x83, 0xf9, 0x5e, 0x0a, 0x8b, 0x68, 0x71, 0x81,
	0x12, 0x83, 0x90, 0x2d, 0x17, 0x77, 0x50, 0x6a, 0x7a, 0x66, 0x71, 0x49, 0x6a, 0x51, 0x68, 0x71,
	0x91, 0x90, 0x28, 0xb2, 0x32, 0xb8, 0x67, 0xa4, 0xb0, 0x09, 0x83, 0xb4, 0x27, 0xb1, 0x81, 0x85,
	0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x26, 0xce, 0xab, 0xe6, 0x82, 0x01, 0x00, 0x00,
}
